version: '3.8'

services:
  app:
    image: snowcrab382/spring-app
    restart: always
    container_name: spring-app
    environment:
      JASYPT_SECRET_KEY: ${JASYPT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: deploy
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shop?useSSL=false&&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - shop-network

  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - shop-network

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      TZ: ${MYSQL_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - shop-network

  mysqld-exporter:
    image: prom/mysqld-exporter
    restart: unless-stopped
    container_name: mysqld-exporter
    environment:
      DATA_SOURCE_NAME: root:${MYSQL_ROOT_PASSWORD}@(mysql:3306)/shop
    command:
      - "--mysqld.username=${MYSQL_USERNAME}:${MYSQL_PASSWORD}"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    depends_on:
      - mysql
    networks:
      - shop-network

  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - shop-network

volumes:
  mysql-data:
  grafana-data:

networks:
  shop-network:
    driver: bridge