global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'spring-app:8080' ]

  - job_name: 'mysqld-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]
