spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_URL}:3306/shop?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

decorator:
  datasource:
    p6spy:
      enable-logging: false
