spring:
  jasypt:
    encryptor:
      password: ${JASYPT_SECRET_KEY}

  flyway:
    enabled: true

  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 100

payment:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  base-url: https://api.tosspayments.com/v1/payments
  confirm-endpoint: /confirm
