spring:
  jasypt:
    encryptor:
      password: ${JASYPT_SECRET_KEY}

  flyway:
    enabled: true

  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 100

payment:
  secret-key: ENC(/zMxUzBbhivsJUrW6PBujFT0Pc+cYkMtduC+d3rE89S9R4yswd0LItNyrqQHKGBs)
  base-url: https://api.tosspayments.com/v1/payments
  confirm-endpoint: /confirm
